### PR TITLE
Add Accent configuration + GitHub Actions workflow

### PR DESCRIPTION
**Pull request by remi**
## 📖 Description

This pull request adds a sample [Accent](https://www.accent.reviews/) configuration and a workflow for GitHub Actions, which sync translations files daily and create a pull request for them.

## 🦀 Dispatch

- `#dispatch/devops`

### CODE REVIEW

**Comment by marcantoinefortier** [comment]
👍🏻 

I'll create a new issue to migrate from using npm's `accent-cli` to a gradle plugin, as this would fit a lot more in _a mobile development project setup_.

**Review by marcantoinefortier — APPROVED** [review]

**Comment by marcantoinefortier** [comment]
@remi We should also update the README to document this feature (what does it do and how to configure it) 🙂

**Comment by remi** [comment]
> @remi We should also update the README to document this feature (what does it do and how to configure it) 🙂

@marcantoinefortier I added a note in `README.md` (which is the boilerplate’s README, not the generated-project’s README) which mentions that an KWord + Accent setup is present in the boilerplate project.

Feel free to push into my branch to improve stuff!

**Comment by remi** [comment]
@marcantoinefortier I’m going to merge this — you can document it in another PR! 🚀

**Pull request merged**
